import wizard
import partner
import purchase
import fleet
import account
import account_asset
import analytic_account
import product
import stock
import account_multi_invoice
import res_company
import account_distribution_plan